### ISSUE TITLE
Failed to set up ceremony when given AWS key is not available

### ISSUE THREAD

**Issue by gurrpi** [quadratic-funding/mpc-phase2-suite#361]
`coordinator setup` command fails with following error:

```
✔ Select the pre-computed zKey file related to the circuit › ProcessMessages_6-8-3-3_test.0.zkey
powersOfTau28_hez_final_23.ptau
✔ Select the Powers of Tau file choosen for the circuit › powersOfTau28_hez_final_23.ptau
🕗  Getting ready for ceremony files and data storage...✖ [functions/internal] internal 
✨  Done in 67.06s.
```

Log of Cloud Function `createBucket`:
```
Error: [ERROR] Generic error when creating a new S3 bucket: InvalidAccessKeyId: The AWS Access Key Id you provided does not exist in our records.
    at entryFromArgs (/workspace/node_modules/firebase-functions/lib/logger/index.js:130:19)
    at Object.error (/workspace/node_modules/firebase-functions/lib/logger/index.js:116:11)
    at logMsg (/workspace/dist/src/functions/index.node.js:126:41)
    at /workspace/dist/src/functions/index.node.js:1890:9
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async /workspace/node_modules/firebase-functions/lib/common/providers/https.js:438:26
```

### Possible Fix

Check AWS key's validity before running setup command

**Comment by 0xjei** [comment]
How are we going to check the keys? Will it be possible to ping the AWS S3 service trying to use that key? Because otherwise until we use them we will never know that they are valid or not
